### ISSUE TITLE
Site title is overflowing >600px

### ISSUE THREAD

**Issue by guytepper** [DrupalHub/dcamp15#25]
![screen shot 2016-09-14 at 10 33 17 am](https://cloud.githubusercontent.com/assets/13344923/18503636/b2921bcc-7a66-11e6-8c76-85b254050320.png)

**Comment by RoySegall** [comment]
You got a basic reaction - Like. If you want a much festive react - create a PR :)

If not it's fine by me. I'll tackle it in the upcoming days.
